import React, { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, HelpCircle, Coins, BookOpen, Shield, Mail, AlertTriangle } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { SPREADS } from '../constants';
import { SpreadType } from '../types';
import Button from './Button';
import { ROUTES } from '../routes/routes';

// Follow-up question cost (same as backend)
const FOLLOW_UP_CREDIT_COST = 1;
const SUPPORT_EMAIL = 'support@celestiarcana.com';

// All translations
const content = {
  en: {
    hero: {
      title: 'Frequently Asked Questions',
      subtitle: 'Everything you need to know about CelestiArcana'
    },
    disclaimer: {
      title: 'Important Notice',
      text: 'CelestiArcana is for entertainment and personal reflection purposes only. Tarot readings provided here are generated by artificial intelligence and should not be considered professional advice (medical, legal, financial, or otherwise). The interpretations offer symbolic guidance and perspective, not predictions of the future. We encourage you to use these readings as a tool for self-reflection, not as a basis for important life decisions. Always consult qualified professionals for serious matters.'
    },
    gettingStarted: {
      title: 'Getting Started',
      q1: 'What is CelestiArcana?',
      a1: "CelestiArcana is an AI-powered tarot reading application. Each reading combines traditional tarot symbolism with personalized interpretation based on your question and the cards drawn. It's designed to offer guidance, perspective, and moments of reflection through the rich imagery of tarot.",
      q2: 'Is this real tarot?',
      a2: 'We use authentic tarot card meanings, traditional spreads, and genuine symbolism from the Rider-Waite-Smith tradition. The interpretations are generated by AI, crafted to be thoughtful and relevant to your situation. Think of it as tarot wisdom made accessible — the cards are real, the meanings are authentic, and the technology helps deliver personalized insights.',
      q3: 'Do I need to know tarot to use this?',
      a3: "Not at all. CelestiArcana is designed for everyone, from complete beginners to experienced readers. Simply ask your question and we'll handle the rest. Each reading explains the cards drawn, their traditional meanings, and how they relate to your specific situation.",
      q4: 'Are the readings accurate predictions?',
      a4: "CelestiArcana does not predict the future. Tarot is a tool for reflection and insight, not divination. Our AI-generated interpretations offer symbolic guidance based on traditional card meanings. They're meant to help you think about your situation from new angles, not to tell you what will happen. The value lies in the perspective and self-reflection they inspire.",
      q5: 'Are the interpretations generated by AI?',
      a5: "Yes. All readings are generated by artificial intelligence. While we've trained our system on authentic tarot meanings and interpretation techniques, AI can make mistakes or produce responses that don't fully resonate with your situation. Use the readings as one perspective among many, and trust your own intuition above all."
    },
    credits: {
      title: 'Credits & Payment',
      q1: 'How do credits work?',
      a1: 'Credits are how you pay for readings. There are no subscriptions or monthly fees — you simply buy credits when you need them, or earn them for free through daily bonuses and referrals.',
      learnMore: 'Learn more about credits',
      q2: 'How much do readings cost?',
      seeFullPricing: 'See full pricing',
      q3: 'Do credits expire?',
      a3: "No. Your credits never expire. They're yours until you use them, whether that's tomorrow or years from now.",
      q4: 'What payment methods do you accept?',
      a4: 'We accept credit and debit cards through Stripe (Visa, Mastercard, American Express, and more) as well as PayPal. All payments are processed securely — we never see or store your payment details.',
      q5: 'Can I get a refund?',
      a5: "We evaluate refund requests on a case-by-case basis. If you're unhappy with a purchase, please contact us at",
      a5b: "and we'll do our best to help."
    },
    readings: {
      title: 'Your Readings',
      q1: 'Are my readings saved?',
      a1: 'Yes. All your readings are automatically saved to your account. You can view your complete reading history anytime from your',
      profile: 'profile page',
      q2: 'Can I ask follow-up questions?',
      q3: 'What spread types are available?',
      a3: 'We offer several spread types to suit different needs:',
      spread1: 'Single Card',
      spread1desc: 'Quick guidance for simple questions',
      spread2: 'Three Card',
      spread2desc: 'Past, present, and future perspective',
      spread5: 'Five Card (Love & Career)',
      spread5desc: '5-card spreads for relationships and career',
      spread3: 'Horseshoe',
      spread3desc: 'Deeper situation analysis with 7 cards',
      spread4: 'Celtic Cross',
      spread4desc: 'Comprehensive 10-card reading for complex questions',
      q4: 'Can I add my own reflections to readings?',
      a4: 'Yes. After each reading, you have the option to write your own reflections and thoughts. This helps you process the reading and creates a personal journal of your tarot journey.',
      q5: 'What languages are supported?',
      a5: 'CelestiArcana is fully available in English and French. You can switch languages anytime using the flag icon in the header. Your readings will be generated in your selected language.',
      credit: 'credit',
      credits: 'credits'
    },
    privacy: {
      title: 'Privacy & Security',
      q1: 'Is my data private?',
      a1: 'Yes. Your readings, questions, and personal reflections are completely private to your account. We do not share, sell, or use your data for any purpose other than providing you with the service. See our',
      privacyPolicy: 'Privacy Policy',
      a1b: 'for complete details.',
      q2: 'Where is my data stored?',
      a2: 'Your data is stored on secure servers in the European Union (Frankfurt, Germany), in compliance with GDPR regulations. We use industry-standard encryption to protect your information.',
      q3: 'How do I delete my account?',
      a3: 'To delete your account and all associated data, please contact us at',
      a3b: "We'll process your request within 30 days and confirm once your data has been permanently deleted.",
      q4: 'Is payment information secure?',
      a4: 'Absolutely. All payments are processed by Stripe and PayPal — industry leaders in payment security. We never see, store, or have access to your credit card numbers or banking details.'
    },
    support: {
      title: 'Support',
      q1: 'How do I contact support?',
      a1: 'Email us at',
      a1b: 'We typically respond within 24-48 hours.',
      q2: 'I have a payment issue',
      a2: "We're sorry to hear that. Please contact us at",
      a2b: "with your payment confirmation or any relevant details. We'll investigate and resolve the issue as quickly as possible.",
      q3: "Something isn't working correctly",
      a3: 'Please email us at',
      a3b: "with a description of the issue, what you were trying to do, and any error messages you saw. Screenshots are always helpful!",
      q4: 'Can I suggest a feature?',
      a4: 'Absolutely! We love hearing from our users. Send your ideas to',
      a4b: 'We read every suggestion and consider them for future updates.'
    },
    cta: {
      title: 'Still have questions?',
      description: "We're here to help. Reach out and we'll get back to you as soon as possible.",
      button: 'Contact Support'
    },
    footer: {
      disclaimer: 'CelestiArcana is intended for entertainment and personal insight only. Readings are AI-generated and should not replace professional advice. By using this service, you agree to our',
      terms: 'Terms of Service'
    }
  },
  fr: {
    hero: {
      title: 'Questions Fréquentes',
      subtitle: 'Tout ce que vous devez savoir sur CelestiArcana'
    },
    disclaimer: {
      title: 'Avis Important',
      text: "CelestiArcana est destiné uniquement au divertissement et à la réflexion personnelle. Les lectures de tarot fournies ici sont générées par intelligence artificielle et ne doivent pas être considérées comme des conseils professionnels (médicaux, juridiques, financiers ou autres). Les interprétations offrent des conseils symboliques et une perspective, pas des prédictions de l'avenir. Nous vous encourageons à utiliser ces lectures comme un outil d'introspection, et non comme base pour des décisions de vie importantes. Consultez toujours des professionnels qualifiés pour les questions sérieuses."
    },
    gettingStarted: {
      title: 'Pour Commencer',
      q1: "Qu'est-ce que CelestiArcana ?",
      a1: "CelestiArcana est une application de lecture de tarot alimentée par l'IA. Chaque lecture combine le symbolisme traditionnel du tarot avec une interprétation personnalisée basée sur votre question et les cartes tirées. Elle est conçue pour offrir des conseils, une perspective et des moments de réflexion à travers l'imagerie riche du tarot.",
      q2: 'Est-ce du vrai tarot ?',
      a2: "Nous utilisons des significations de cartes de tarot authentiques, des tirages traditionnels et un symbolisme authentique de la tradition Rider-Waite-Smith. Les interprétations sont générées par l'IA, conçues pour être réfléchies et pertinentes par rapport à votre situation. Voyez cela comme la sagesse du tarot rendue accessible — les cartes sont réelles, les significations sont authentiques, et la technologie aide à fournir des aperçus personnalisés.",
      q3: 'Dois-je connaître le tarot pour utiliser ce service ?',
      a3: "Pas du tout. CelestiArcana est conçu pour tout le monde, des débutants complets aux lecteurs expérimentés. Posez simplement votre question et nous nous occupons du reste. Chaque lecture explique les cartes tirées, leurs significations traditionnelles, et comment elles se rapportent à votre situation spécifique.",
      q4: 'Les lectures sont-elles des prédictions exactes ?',
      a4: "CelestiArcana ne prédit pas l'avenir. Le tarot est un outil de réflexion et d'introspection, pas de divination. Nos interprétations générées par l'IA offrent des conseils symboliques basés sur les significations traditionnelles des cartes. Elles sont destinées à vous aider à réfléchir à votre situation sous de nouveaux angles, pas à vous dire ce qui va se passer. La valeur réside dans la perspective et l'introspection qu'elles inspirent.",
      q5: "Les interprétations sont-elles générées par l'IA ?",
      a5: "Oui. Toutes les lectures sont générées par intelligence artificielle. Bien que nous ayons formé notre système sur des significations de tarot authentiques et des techniques d'interprétation, l'IA peut faire des erreurs ou produire des réponses qui ne résonnent pas entièrement avec votre situation. Utilisez les lectures comme une perspective parmi d'autres, et faites confiance à votre propre intuition avant tout."
    },
    credits: {
      title: 'Crédits & Paiement',
      q1: 'Comment fonctionnent les crédits ?',
      a1: "Les crédits sont votre moyen de paiement pour les lectures. Il n'y a pas d'abonnements ni de frais mensuels — vous achetez simplement des crédits quand vous en avez besoin, ou vous les gagnez gratuitement grâce aux bonus quotidiens et aux parrainages.",
      learnMore: 'En savoir plus sur les crédits',
      q2: 'Combien coûtent les lectures ?',
      seeFullPricing: 'Voir tous les tarifs',
      q3: 'Les crédits expirent-ils ?',
      a3: "Non. Vos crédits n'expirent jamais. Ils sont à vous jusqu'à ce que vous les utilisiez, que ce soit demain ou dans des années.",
      q4: 'Quels modes de paiement acceptez-vous ?',
      a4: 'Nous acceptons les cartes de crédit et de débit via Stripe (Visa, Mastercard, American Express, et plus) ainsi que PayPal. Tous les paiements sont traités de manière sécurisée — nous ne voyons ni ne stockons jamais vos détails de paiement.',
      q5: 'Puis-je obtenir un remboursement ?',
      a5: "Nous évaluons les demandes de remboursement au cas par cas. Si vous n'êtes pas satisfait d'un achat, veuillez nous contacter à",
      a5b: 'et nous ferons de notre mieux pour vous aider.'
    },
    readings: {
      title: 'Vos Lectures',
      q1: 'Mes lectures sont-elles sauvegardées ?',
      a1: 'Oui. Toutes vos lectures sont automatiquement sauvegardées dans votre compte. Vous pouvez consulter votre historique complet de lectures à tout moment depuis votre',
      profile: 'page de profil',
      q2: 'Puis-je poser des questions de suivi ?',
      q3: 'Quels types de tirages sont disponibles ?',
      a3: 'Nous offrons plusieurs types de tirages pour répondre à différents besoins :',
      spread1: 'Carte Unique',
      spread1desc: 'Guidance rapide pour des questions simples',
      spread2: 'Trois Cartes',
      spread2desc: 'Perspective passé, présent et futur',
      spread5: 'Cinq Cartes (Amour & Carrière)',
      spread5desc: 'Tirages à 5 cartes pour les relations et la carrière',
      spread3: 'Fer à Cheval',
      spread3desc: 'Analyse plus approfondie avec 7 cartes',
      spread4: 'Croix Celtique',
      spread4desc: 'Lecture complète à 10 cartes pour les questions complexes',
      q4: 'Puis-je ajouter mes propres réflexions aux lectures ?',
      a4: "Oui. Après chaque lecture, vous avez la possibilité d'écrire vos propres réflexions et pensées. Cela vous aide à traiter la lecture et crée un journal personnel de votre parcours tarot.",
      q5: 'Quelles langues sont prises en charge ?',
      a5: "CelestiArcana est entièrement disponible en anglais et en français. Vous pouvez changer de langue à tout moment en utilisant l'icône de drapeau dans l'en-tête. Vos lectures seront générées dans la langue sélectionnée.",
      credit: 'crédit',
      credits: 'crédits'
    },
    privacy: {
      title: 'Confidentialité & Sécurité',
      q1: 'Mes données sont-elles privées ?',
      a1: 'Oui. Vos lectures, questions et réflexions personnelles sont entièrement privées de votre compte. Nous ne partageons, ne vendons ni n\'utilisons vos données à d\'autres fins que de vous fournir le service. Consultez notre',
      privacyPolicy: 'Politique de Confidentialité',
      a1b: 'pour tous les détails.',
      q2: 'Où sont stockées mes données ?',
      a2: "Vos données sont stockées sur des serveurs sécurisés dans l'Union européenne (Francfort, Allemagne), conformément aux réglementations RGPD. Nous utilisons un cryptage aux normes de l'industrie pour protéger vos informations.",
      q3: 'Comment supprimer mon compte ?',
      a3: 'Pour supprimer votre compte et toutes les données associées, veuillez nous contacter à',
      a3b: 'Nous traiterons votre demande dans les 30 jours et confirmerons une fois que vos données auront été définitivement supprimées.',
      q4: 'Les informations de paiement sont-elles sécurisées ?',
      a4: "Absolument. Tous les paiements sont traités par Stripe et PayPal — leaders de l'industrie en matière de sécurité des paiements. Nous ne voyons, ne stockons ni n'avons accès à vos numéros de carte de crédit ou coordonnées bancaires."
    },
    support: {
      title: 'Support',
      q1: 'Comment contacter le support ?',
      a1: 'Envoyez-nous un email à',
      a1b: 'Nous répondons généralement sous 24-48 heures.',
      q2: "J'ai un problème de paiement",
      a2: 'Nous sommes désolés de l\'apprendre. Veuillez nous contacter à',
      a2b: "avec votre confirmation de paiement ou tout détail pertinent. Nous enquêterons et résoudrons le problème aussi rapidement que possible.",
      q3: 'Quelque chose ne fonctionne pas correctement',
      a3: 'Veuillez nous envoyer un email à',
      a3b: "avec une description du problème, ce que vous essayiez de faire, et tout message d'erreur que vous avez vu. Les captures d'écran sont toujours utiles !",
      q4: 'Puis-je suggérer une fonctionnalité ?',
      a4: 'Absolument ! Nous aimons avoir des nouvelles de nos utilisateurs. Envoyez vos idées à',
      a4b: 'Nous lisons chaque suggestion et les considérons pour les futures mises à jour.'
    },
    cta: {
      title: 'Encore des questions ?',
      description: 'Nous sommes là pour vous aider. Contactez-nous et nous vous répondrons dès que possible.',
      button: 'Contacter le Support'
    },
    footer: {
      disclaimer: "CelestiArcana est destiné uniquement au divertissement et à l'introspection personnelle. Les lectures sont générées par l'IA et ne doivent pas remplacer les conseils professionnels. En utilisant ce service, vous acceptez nos",
      terms: "Conditions d'Utilisation"
    }
  }
};

interface FAQItemProps {
  question: string;
  answer: React.ReactNode;
  isOpen: boolean;
  onToggle: () => void;
}

const FAQItem: React.FC<FAQItemProps> = ({ question, answer, isOpen, onToggle }) => {
  return (
    <div className="border border-white/10 rounded-lg overflow-hidden bg-slate-900/30 hover:border-purple-500/30 transition-colors">
      <button
        onClick={onToggle}
        className="w-full px-5 py-4 flex items-center justify-between text-left"
      >
        <span className="text-slate-200 font-medium pr-4">{question}</span>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
          className="flex-shrink-0"
        >
          <ChevronDown className="w-5 h-5 text-slate-400" />
        </motion.div>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            <div className="px-5 pb-4 text-slate-400 text-sm leading-relaxed border-t border-white/5 pt-3">
              {answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

interface FAQSectionProps {
  title: string;
  icon: React.ReactNode;
  iconColor: string;
  children: React.ReactNode;
}

const FAQSection: React.FC<FAQSectionProps> = ({ title, icon, iconColor, children }) => {
  return (
    <div className="mb-10">
      <div className="flex items-center gap-3 mb-4">
        <div className={`w-10 h-10 rounded-full ${iconColor} flex items-center justify-center`}>
          {icon}
        </div>
        <h2 className="text-xl font-heading text-amber-100">{title}</h2>
      </div>
      <div className="space-y-3">
        {children}
      </div>
    </div>
  );
};

const FAQ: React.FC = () => {
  const { language } = useApp();
  const [openItems, setOpenItems] = useState<Set<string>>(new Set());

  // Get translations for current language
  const t = content[language];

  const toggleItem = useCallback((id: string) => {
    setOpenItems(prev => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  }, []);

  // Get actual costs from constants (with safe access for spreads that may not exist)
  const singleCardCost = SPREADS[SpreadType.SINGLE]?.cost ?? 1;
  const threeCardCost = SPREADS[SpreadType.THREE_CARD]?.cost ?? 3;
  const fiveCardCost = SPREADS[SpreadType.FIVE_CARD]?.cost ?? 5;
  const horseshoeCost = SPREADS[SpreadType.HORSESHOE]?.cost ?? 7;
  const celticCrossCost = SPREADS[SpreadType.CELTIC_CROSS]?.cost ?? 10;

  // Helper to create styled links
  const StyledLink = ({ to, children }: { to: string; children: React.ReactNode }) => (
    <Link
      to={to}
      className="text-purple-400 hover:text-purple-300 underline underline-offset-2 transition-colors"
    >
      {children}
    </Link>
  );

  return (
    <div className="min-h-screen pb-20">
      {/* Hero Section */}
      <section className="relative py-16 px-4 text-center overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-purple-600/10 rounded-full blur-3xl -z-10" />

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="w-16 h-16 mx-auto mb-6 bg-gradient-to-br from-purple-500 to-indigo-600 rounded-full flex items-center justify-center">
            <HelpCircle className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-4xl md:text-5xl font-heading font-bold text-transparent bg-clip-text bg-gradient-to-b from-amber-100 to-purple-300 mb-4">
            {t.hero.title}
          </h1>
          <p className="text-lg text-slate-300 max-w-xl mx-auto">
            {t.hero.subtitle}
          </p>
        </motion.div>
      </section>

      <div className="max-w-3xl mx-auto px-4">
        {/* Important Disclaimer */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mb-10 p-5 bg-amber-900/20 border border-amber-500/30 rounded-xl"
        >
          <div className="flex items-start gap-4">
            <div className="w-10 h-10 bg-amber-500/20 rounded-full flex items-center justify-center flex-shrink-0">
              <AlertTriangle className="w-5 h-5 text-amber-400" />
            </div>
            <div>
              <h3 className="text-amber-200 font-medium mb-2">
                {t.disclaimer.title}
              </h3>
              <p className="text-sm text-amber-200/70 leading-relaxed">
                {t.disclaimer.text}
              </p>
            </div>
          </div>
        </motion.div>

        {/* Getting Started */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <FAQSection
            title={t.gettingStarted.title}
            icon={<BookOpen className="w-5 h-5 text-white" />}
            iconColor="bg-cyan-500/30"
          >
            <FAQItem
              question={t.gettingStarted.q1}
              answer={t.gettingStarted.a1}
              isOpen={openItems.has('gs-1')}
              onToggle={() => toggleItem('gs-1')}
            />
            <FAQItem
              question={t.gettingStarted.q2}
              answer={t.gettingStarted.a2}
              isOpen={openItems.has('gs-2')}
              onToggle={() => toggleItem('gs-2')}
            />
            <FAQItem
              question={t.gettingStarted.q3}
              answer={t.gettingStarted.a3}
              isOpen={openItems.has('gs-3')}
              onToggle={() => toggleItem('gs-3')}
            />
            <FAQItem
              question={t.gettingStarted.q4}
              answer={t.gettingStarted.a4}
              isOpen={openItems.has('gs-4')}
              onToggle={() => toggleItem('gs-4')}
            />
            <FAQItem
              question={t.gettingStarted.q5}
              answer={t.gettingStarted.a5}
              isOpen={openItems.has('gs-5')}
              onToggle={() => toggleItem('gs-5')}
            />
          </FAQSection>
        </motion.div>

        {/* Credits & Payment */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          <FAQSection
            title={t.credits.title}
            icon={<Coins className="w-5 h-5 text-white" />}
            iconColor="bg-amber-500/30"
          >
            <FAQItem
              question={t.credits.q1}
              answer={
                <span>
                  {t.credits.a1}{' '}
                  <StyledLink to={ROUTES.HOW_CREDITS_WORK}>{t.credits.learnMore}</StyledLink>
                </span>
              }
              isOpen={openItems.has('cp-1')}
              onToggle={() => toggleItem('cp-1')}
            />
            <FAQItem
              question={t.credits.q2}
              answer={
                <span>
                  {language === 'en'
                    ? `A Single Card reading costs ${singleCardCost} credit. Three Card spreads cost ${threeCardCost} credits. Five Card spreads (Love & Career) cost ${fiveCardCost} credits. Horseshoe spreads cost ${horseshoeCost} credits. The comprehensive Celtic Cross costs ${celticCrossCost} credits. Follow-up questions: 2 questions for ${FOLLOW_UP_CREDIT_COST} credit.`
                    : `Une lecture Carte Unique coûte ${singleCardCost} crédit. Les tirages à Trois Cartes coûtent ${threeCardCost} crédits. Les tirages à Cinq Cartes (Amour & Carrière) coûtent ${fiveCardCost} crédits. Les tirages Fer à Cheval coûtent ${horseshoeCost} crédits. La Croix Celtique complète coûte ${celticCrossCost} crédits. Questions de suivi : 2 questions pour ${FOLLOW_UP_CREDIT_COST} crédit.`
                  }{' '}
                  <StyledLink to={ROUTES.HOW_CREDITS_WORK}>{t.credits.seeFullPricing}</StyledLink>
                </span>
              }
              isOpen={openItems.has('cp-2')}
              onToggle={() => toggleItem('cp-2')}
            />
            <FAQItem
              question={t.credits.q3}
              answer={t.credits.a3}
              isOpen={openItems.has('cp-3')}
              onToggle={() => toggleItem('cp-3')}
            />
            <FAQItem
              question={t.credits.q4}
              answer={t.credits.a4}
              isOpen={openItems.has('cp-4')}
              onToggle={() => toggleItem('cp-4')}
            />
            <FAQItem
              question={t.credits.q5}
              answer={
                <span>
                  {t.credits.a5}{' '}
                  <a href={`mailto:${SUPPORT_EMAIL}`} className="text-purple-400 hover:text-purple-300 underline underline-offset-2">
                    {SUPPORT_EMAIL}
                  </a>{' '}
                  {t.credits.a5b}
                </span>
              }
              isOpen={openItems.has('cp-5')}
              onToggle={() => toggleItem('cp-5')}
            />
          </FAQSection>
        </motion.div>

        {/* Your Readings */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <FAQSection
            title={t.readings.title}
            icon={<BookOpen className="w-5 h-5 text-white" />}
            iconColor="bg-purple-500/30"
          >
            <FAQItem
              question={t.readings.q1}
              answer={
                <span>
                  {t.readings.a1}{' '}
                  <StyledLink to={ROUTES.PROFILE}>{t.readings.profile}</StyledLink>.
                </span>
              }
              isOpen={openItems.has('yr-1')}
              onToggle={() => toggleItem('yr-1')}
            />
            <FAQItem
              question={t.readings.q2}
              answer={
                language === 'en'
                  ? `Yes. After receiving your reading, you can ask follow-up questions to dive deeper or clarify specific aspects. You get 2 follow-up questions for ${FOLLOW_UP_CREDIT_COST} credit.`
                  : `Oui. Après avoir reçu votre lecture, vous pouvez poser des questions de suivi pour approfondir ou clarifier des aspects spécifiques. Vous obtenez 2 questions de suivi pour ${FOLLOW_UP_CREDIT_COST} crédit.`
              }
              isOpen={openItems.has('yr-2')}
              onToggle={() => toggleItem('yr-2')}
            />
            <FAQItem
              question={t.readings.q3}
              answer={
                <span>
                  {t.readings.a3}<br /><br />
                  <strong className="text-slate-300">{t.readings.spread1}</strong> ({singleCardCost} {singleCardCost === 1 ? t.readings.credit : t.readings.credits}) — {t.readings.spread1desc}<br />
                  <strong className="text-slate-300">{t.readings.spread2}</strong> ({threeCardCost} {t.readings.credits}) — {t.readings.spread2desc}<br />
                  <strong className="text-slate-300">{t.readings.spread5}</strong> ({fiveCardCost} {t.readings.credits}) — {t.readings.spread5desc}<br />
                  <strong className="text-slate-300">{t.readings.spread3}</strong> ({horseshoeCost} {t.readings.credits}) — {t.readings.spread3desc}<br />
                  <strong className="text-slate-300">{t.readings.spread4}</strong> ({celticCrossCost} {t.readings.credits}) — {t.readings.spread4desc}
                </span>
              }
              isOpen={openItems.has('yr-3')}
              onToggle={() => toggleItem('yr-3')}
            />
            <FAQItem
              question={t.readings.q4}
              answer={t.readings.a4}
              isOpen={openItems.has('yr-4')}
              onToggle={() => toggleItem('yr-4')}
            />
            <FAQItem
              question={t.readings.q5}
              answer={t.readings.a5}
              isOpen={openItems.has('yr-5')}
              onToggle={() => toggleItem('yr-5')}
            />
          </FAQSection>
        </motion.div>

        {/* Privacy & Security */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          <FAQSection
            title={t.privacy.title}
            icon={<Shield className="w-5 h-5 text-white" />}
            iconColor="bg-green-500/30"
          >
            <FAQItem
              question={t.privacy.q1}
              answer={
                <span>
                  {t.privacy.a1}{' '}
                  <StyledLink to={ROUTES.PRIVACY}>{t.privacy.privacyPolicy}</StyledLink>{' '}
                  {t.privacy.a1b}
                </span>
              }
              isOpen={openItems.has('ps-1')}
              onToggle={() => toggleItem('ps-1')}
            />
            <FAQItem
              question={t.privacy.q2}
              answer={t.privacy.a2}
              isOpen={openItems.has('ps-2')}
              onToggle={() => toggleItem('ps-2')}
            />
            <FAQItem
              question={t.privacy.q3}
              answer={
                <span>
                  {t.privacy.a3}{' '}
                  <a href={`mailto:${SUPPORT_EMAIL}`} className="text-purple-400 hover:text-purple-300 underline underline-offset-2">
                    {SUPPORT_EMAIL}
                  </a>.{' '}
                  {t.privacy.a3b}
                </span>
              }
              isOpen={openItems.has('ps-3')}
              onToggle={() => toggleItem('ps-3')}
            />
            <FAQItem
              question={t.privacy.q4}
              answer={t.privacy.a4}
              isOpen={openItems.has('ps-4')}
              onToggle={() => toggleItem('ps-4')}
            />
          </FAQSection>
        </motion.div>

        {/* Support */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.4 }}
        >
          <FAQSection
            title={t.support.title}
            icon={<Mail className="w-5 h-5 text-white" />}
            iconColor="bg-indigo-500/30"
          >
            <FAQItem
              question={t.support.q1}
              answer={
                <span>
                  {t.support.a1}{' '}
                  <a href={`mailto:${SUPPORT_EMAIL}`} className="text-purple-400 hover:text-purple-300 underline underline-offset-2">
                    {SUPPORT_EMAIL}
                  </a>.{' '}
                  {t.support.a1b}
                </span>
              }
              isOpen={openItems.has('sp-1')}
              onToggle={() => toggleItem('sp-1')}
            />
            <FAQItem
              question={t.support.q2}
              answer={
                <span>
                  {t.support.a2}{' '}
                  <a href={`mailto:${SUPPORT_EMAIL}`} className="text-purple-400 hover:text-purple-300 underline underline-offset-2">
                    {SUPPORT_EMAIL}
                  </a>{' '}
                  {t.support.a2b}
                </span>
              }
              isOpen={openItems.has('sp-2')}
              onToggle={() => toggleItem('sp-2')}
            />
            <FAQItem
              question={t.support.q3}
              answer={
                <span>
                  {t.support.a3}{' '}
                  <a href={`mailto:${SUPPORT_EMAIL}`} className="text-purple-400 hover:text-purple-300 underline underline-offset-2">
                    {SUPPORT_EMAIL}
                  </a>{' '}
                  {t.support.a3b}
                </span>
              }
              isOpen={openItems.has('sp-3')}
              onToggle={() => toggleItem('sp-3')}
            />
            <FAQItem
              question={t.support.q4}
              answer={
                <span>
                  {t.support.a4}{' '}
                  <a href={`mailto:${SUPPORT_EMAIL}`} className="text-purple-400 hover:text-purple-300 underline underline-offset-2">
                    {SUPPORT_EMAIL}
                  </a>.{' '}
                  {t.support.a4b}
                </span>
              }
              isOpen={openItems.has('sp-4')}
              onToggle={() => toggleItem('sp-4')}
            />
          </FAQSection>
        </motion.div>

        {/* Still have questions CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.5 }}
          className="text-center py-10 mt-6"
        >
          <div className="bg-gradient-to-r from-purple-900/30 via-slate-900/50 to-purple-900/30 border border-purple-500/20 rounded-2xl p-8">
            <h2 className="text-xl font-heading text-amber-100 mb-3">
              {t.cta.title}
            </h2>
            <p className="text-slate-400 mb-6 max-w-md mx-auto">
              {t.cta.description}
            </p>
            <Button
              onClick={() => window.location.href = `mailto:${SUPPORT_EMAIL}`}
              className="inline-flex items-center gap-2"
            >
              <Mail className="w-4 h-4" />
              {t.cta.button}
            </Button>
          </div>
        </motion.div>

        {/* Final disclaimer */}
        <div className="text-center text-xs text-slate-500 mt-8 pb-8">
          <p>
            {t.footer.disclaimer}{' '}
            <StyledLink to={ROUTES.TERMS}>{t.footer.terms}</StyledLink>.
          </p>
        </div>
      </div>
    </div>
  );
};

export default FAQ;
