import React from 'react';
import { useApp } from '../../context/AppContext';
import { FileText, AlertTriangle, CreditCard, Users, Scale, Mail } from 'lucide-react';

const TermsOfService: React.FC = () => {
  const { language } = useApp();

  const content = {
    en: {
      title: 'Terms of Service',
      subtitle: 'Conditions d\'Utilisation',
      lastUpdated: 'Last updated: December 2024',

      sections: [
        {
          icon: FileText,
          title: '1. Acceptance of Terms',
          content: `By accessing or using MysticOracle ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.

**Service Provider:**
MysticOracle is operated by [Company Name], registered in France.
**SIRET:** [Your SIRET Number]
**Contact:** contact@mysticoracle.com`
        },
        {
          icon: AlertTriangle,
          title: '2. Nature of Service',
          content: `**Entertainment Purpose Only:**
MysticOracle provides AI-powered tarot readings, horoscopes, and oracle consultations for entertainment and personal reflection purposes only.

**Important Disclaimers:**
• Our readings are NOT professional advice (medical, legal, financial, or psychological)
• Results are generated by artificial intelligence and should not be relied upon for important life decisions
• We do not claim supernatural or psychic abilities
• Users should consult qualified professionals for any serious matters

**Age Requirement:**
You must be at least 16 years old to use this Service. Users between 13-16 may use the Service with parental consent.`
        },
        {
          icon: CreditCard,
          title: '3. Credits & Payments',
          content: `**Credit System:**
• Credits are required to access tarot readings and other features
• New users receive 10 free credits upon registration
• Additional credits can be purchased through our payment providers (Stripe/PayPal)

**Pricing:**
• All prices are displayed in Euros (EUR)
• Prices include applicable VAT for EU customers

**Refund Policy:**
• Unused credits may be refunded within 14 days of purchase (EU withdrawal right)
• Credits that have been used cannot be refunded
• To request a refund, contact: refunds@mysticoracle.com

**Credit Expiration:**
• Purchased credits do not expire
• Bonus/promotional credits may have expiration dates as specified`
        },
        {
          icon: Users,
          title: '4. User Conduct',
          content: `**You agree NOT to:**
• Use the Service for any illegal purpose
• Attempt to gain unauthorized access to our systems
• Share your account credentials with others
• Create multiple accounts to abuse promotional offers
• Use automated systems or bots to access the Service
• Harass, abuse, or harm other users
• Collect or store personal data of other users

**Account Termination:**
We reserve the right to suspend or terminate accounts that violate these Terms without prior notice.`
        },
        {
          icon: FileText,
          title: '5. Intellectual Property',
          content: `**Our Content:**
• All content on MysticOracle (text, graphics, logos, software) is owned by us or our licensors
• You may not reproduce, distribute, or create derivative works without permission

**Your Content:**
• You retain ownership of any personal content you submit
• By using the Service, you grant us a limited license to process your queries for providing readings

**AI-Generated Content:**
• Readings generated by our AI are provided for your personal use
• You may share your readings but may not commercialize them`
        },
        {
          icon: Scale,
          title: '6. Limitation of Liability',
          content: `**To the maximum extent permitted by law:**

• The Service is provided "AS IS" without warranties of any kind
• We are not liable for any indirect, incidental, or consequential damages
• Our total liability shall not exceed the amount you paid in the last 12 months
• We are not responsible for decisions made based on our readings

**Force Majeure:**
We are not liable for failures due to circumstances beyond our control (natural disasters, internet outages, etc.).`
        },
        {
          icon: Scale,
          title: '7. Governing Law & Disputes',
          content: `**Applicable Law:**
These Terms are governed by French law.

**Dispute Resolution:**
• We encourage you to contact us first to resolve any disputes amicably
• For EU consumers: You may use the EU Online Dispute Resolution platform at https://ec.europa.eu/consumers/odr
• Jurisdiction: Courts of [City], France

**Consumer Rights:**
Nothing in these Terms affects your statutory rights as a consumer under French and EU law.`
        },
        {
          icon: FileText,
          title: '8. Changes to Terms',
          content: `**Modifications:**
• We may update these Terms at any time
• Significant changes will be notified via email or in-app notification
• Continued use after changes constitutes acceptance of new Terms

**Version History:**
• Current version: 1.0
• Effective date: December 2024`
        },
        {
          icon: Mail,
          title: '9. Contact Us',
          content: `For any questions about these Terms:

**Email:** contact@mysticoracle.com
**Address:** [Company Address], France

**Customer Support:**
Response time: Within 48 hours on business days`
        }
      ]
    },
    fr: {
      title: 'Conditions d\'Utilisation',
      subtitle: 'Terms of Service',
      lastUpdated: 'Dernière mise à jour : Décembre 2024',

      sections: [
        {
          icon: FileText,
          title: '1. Acceptation des Conditions',
          content: `En accédant ou en utilisant MysticOracle ("le Service"), vous acceptez d'être lié par ces Conditions d'Utilisation ("Conditions"). Si vous n'acceptez pas ces Conditions, veuillez ne pas utiliser notre Service.

**Fournisseur du Service :**
MysticOracle est exploité par [Nom de la Société], enregistrée en France.
**SIRET :** [Votre Numéro SIRET]
**Contact :** contact@mysticoracle.com`
        },
        {
          icon: AlertTriangle,
          title: '2. Nature du Service',
          content: `**À des Fins de Divertissement Uniquement :**
MysticOracle fournit des lectures de tarot, horoscopes et consultations d'oracle alimentés par l'IA à des fins de divertissement et de réflexion personnelle uniquement.

**Avertissements Importants :**
• Nos lectures ne constituent PAS des conseils professionnels (médicaux, juridiques, financiers ou psychologiques)
• Les résultats sont générés par l'intelligence artificielle et ne doivent pas être utilisés pour des décisions importantes
• Nous ne revendiquons aucune capacité surnaturelle ou psychique
• Les utilisateurs doivent consulter des professionnels qualifiés pour toute question sérieuse

**Condition d'Âge :**
Vous devez avoir au moins 16 ans pour utiliser ce Service. Les utilisateurs entre 13 et 16 ans peuvent utiliser le Service avec le consentement parental.`
        },
        {
          icon: CreditCard,
          title: '3. Crédits et Paiements',
          content: `**Système de Crédits :**
• Des crédits sont nécessaires pour accéder aux lectures de tarot et autres fonctionnalités
• Les nouveaux utilisateurs reçoivent 10 crédits gratuits lors de l'inscription
• Des crédits supplémentaires peuvent être achetés via nos prestataires de paiement (Stripe/PayPal)

**Tarification :**
• Tous les prix sont affichés en Euros (EUR)
• Les prix incluent la TVA applicable pour les clients de l'UE

**Politique de Remboursement :**
• Les crédits non utilisés peuvent être remboursés dans les 14 jours suivant l'achat (droit de rétractation UE)
• Les crédits utilisés ne peuvent pas être remboursés
• Pour demander un remboursement, contactez : refunds@mysticoracle.com

**Expiration des Crédits :**
• Les crédits achetés n'expirent pas
• Les crédits bonus/promotionnels peuvent avoir des dates d'expiration spécifiées`
        },
        {
          icon: Users,
          title: '4. Conduite des Utilisateurs',
          content: `**Vous acceptez de NE PAS :**
• Utiliser le Service à des fins illégales
• Tenter d'accéder sans autorisation à nos systèmes
• Partager vos identifiants de compte avec d'autres
• Créer plusieurs comptes pour abuser des offres promotionnelles
• Utiliser des systèmes automatisés ou des bots pour accéder au Service
• Harceler, abuser ou nuire à d'autres utilisateurs
• Collecter ou stocker des données personnelles d'autres utilisateurs

**Résiliation de Compte :**
Nous nous réservons le droit de suspendre ou de résilier les comptes qui enfreignent ces Conditions sans préavis.`
        },
        {
          icon: FileText,
          title: '5. Propriété Intellectuelle',
          content: `**Notre Contenu :**
• Tout le contenu sur MysticOracle (texte, graphiques, logos, logiciels) nous appartient ou appartient à nos concédants
• Vous ne pouvez pas reproduire, distribuer ou créer des œuvres dérivées sans autorisation

**Votre Contenu :**
• Vous conservez la propriété de tout contenu personnel que vous soumettez
• En utilisant le Service, vous nous accordez une licence limitée pour traiter vos requêtes afin de fournir des lectures

**Contenu Généré par l'IA :**
• Les lectures générées par notre IA sont fournies pour votre usage personnel
• Vous pouvez partager vos lectures mais ne pouvez pas les commercialiser`
        },
        {
          icon: Scale,
          title: '6. Limitation de Responsabilité',
          content: `**Dans les limites autorisées par la loi :**

• Le Service est fourni "EN L'ÉTAT" sans garantie d'aucune sorte
• Nous ne sommes pas responsables des dommages indirects, accessoires ou consécutifs
• Notre responsabilité totale ne dépassera pas le montant que vous avez payé au cours des 12 derniers mois
• Nous ne sommes pas responsables des décisions prises sur la base de nos lectures

**Force Majeure :**
Nous ne sommes pas responsables des défaillances dues à des circonstances hors de notre contrôle (catastrophes naturelles, pannes internet, etc.).`
        },
        {
          icon: Scale,
          title: '7. Loi Applicable et Litiges',
          content: `**Loi Applicable :**
Ces Conditions sont régies par le droit français.

**Résolution des Litiges :**
• Nous vous encourageons à nous contacter d'abord pour résoudre tout litige à l'amiable
• Pour les consommateurs de l'UE : Vous pouvez utiliser la plateforme de Règlement en Ligne des Litiges de l'UE à https://ec.europa.eu/consumers/odr
• Juridiction : Tribunaux de [Ville], France

**Droits des Consommateurs :**
Rien dans ces Conditions n'affecte vos droits légaux en tant que consommateur en vertu du droit français et européen.`
        },
        {
          icon: FileText,
          title: '8. Modifications des Conditions',
          content: `**Modifications :**
• Nous pouvons mettre à jour ces Conditions à tout moment
• Les changements significatifs seront notifiés par email ou notification dans l'application
• L'utilisation continue après les modifications constitue l'acceptation des nouvelles Conditions

**Historique des Versions :**
• Version actuelle : 1.0
• Date d'entrée en vigueur : Décembre 2024`
        },
        {
          icon: Mail,
          title: '9. Nous Contacter',
          content: `Pour toute question concernant ces Conditions :

**Email :** contact@mysticoracle.com
**Adresse :** [Adresse de la Société], France

**Support Client :**
Délai de réponse : Sous 48 heures les jours ouvrables`
        }
      ]
    }
  };

  const t = content[language];

  return (
    <div className="min-h-screen py-12 px-4 relative z-10">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-heading font-bold text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-purple-300 mb-2">
            {t.title}
          </h1>
          <p className="text-slate-400 text-sm italic">{t.subtitle}</p>
          <p className="text-slate-500 text-sm mt-4">{t.lastUpdated}</p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {t.sections.map((section, index) => {
            const Icon = section.icon;
            return (
              <div
                key={index}
                className="bg-slate-900/60 rounded-xl border border-purple-500/20 p-6 md:p-8"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="p-2 bg-purple-500/10 rounded-lg">
                    <Icon className="w-5 h-5 text-purple-400" />
                  </div>
                  <h2 className="text-xl font-heading text-purple-200">
                    {section.title}
                  </h2>
                </div>
                <div className="text-slate-300 prose prose-invert prose-sm max-w-none">
                  {section.content.split('\n\n').map((paragraph, pIndex) => (
                    <div key={pIndex} className="mb-4">
                      {paragraph.split('\n').map((line, lIndex) => {
                        const formattedLine = line.replace(
                          /\*\*(.*?)\*\*/g,
                          '<strong class="text-purple-200">$1</strong>'
                        );
                        if (line.startsWith('•')) {
                          return (
                            <p
                              key={lIndex}
                              className="ml-4 text-slate-400"
                              dangerouslySetInnerHTML={{ __html: formattedLine }}
                            />
                          );
                        }
                        return (
                          <p
                            key={lIndex}
                            dangerouslySetInnerHTML={{ __html: formattedLine }}
                          />
                        );
                      })}
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer Note */}
        <div className="mt-12 text-center text-slate-500 text-sm">
          <p>
            {language === 'en'
              ? 'These Terms of Service comply with French and EU consumer protection laws.'
              : 'Ces Conditions d\'Utilisation sont conformes aux lois françaises et européennes de protection des consommateurs.'}
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
